### Listar disciplinas
GET http://127.0.0.1:5000/disciplinas

###

### Criar disciplina
POST http://127.0.0.1:5000/disciplinas
Content-Type: application/json

{
    "nome": "Matemática"
}


### Excluir disciplina
DELETE http://127.0.0.1:5000/disciplinas/1